# Generated by Django 3.0.4 on 2020-03-20 16:16

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo_1',
            field=models.ImageField(blank=True, upload_to=product.models.Product.get_image_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo_2',
            field=models.ImageField(blank=True, upload_to=product.models.Product.get_image_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo_3',
            field=models.ImageField(blank=True, upload_to=product.models.Product.get_image_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo_4',
            field=models.ImageField(blank=True, upload_to=product.models.Product.get_image_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo_5',
            field=models.ImageField(blank=True, upload_to=product.models.Product.get_image_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo_6',
            field=models.ImageField(blank=True, upload_to=product.models.Product.get_image_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo_main',
            field=models.ImageField(upload_to=product.models.Product.get_image_path),
        ),
    ]
