# Generated by Django 3.0.4 on 2020-03-24 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isTrending',
            field=models.BooleanField(default=False),
        ),
    ]
