# Generated by Django 3.0.4 on 2020-03-25 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='city',
        ),
    ]
