# Generated by Django 3.0.4 on 2020-03-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_remove_product_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='city_name',
            field=models.CharField(blank=True, choices=[('Alexandria', 'Alexandria'), ('Aswan', 'Aswan'), ('Asyut', 'Asyut'), ('Beheira', 'Beheira'), ('Beni Suef', 'Beni Suef'), ('Cairo', 'Cairo')], max_length=150, null=True),
        ),
    ]
