cities_choices = {
        'Alexandria' : 'Alexandria',
        'Aswan' :'Aswan' ,
        'Asyut' : 'Asyut',
        'Beheira' : 'Beheira' ,
        'Beni Suef' : 'Beni Suef',
        'Cairo' : 'Cairo',
        'Dakahlia' : 'Dakahlia',
        'Damietta' : 'Damietta',
        'Faiyum':'Faiyum',
        'Gharbia':'Gharbia',
        'Giza':'Giza',
        'Ismailia':'Ismailia',
        'Kafr El Sheikh':'Kafr El Sheikh',
        'Luxor':'Luxor',
        'Matruh':'Matruh',
        'Minya':'Minya',
        'Monufia':'Monufia',
        'New Valley':'New Valley',
        'North Sinai':'North Sinai',
        'Port Said':'Port Said',
        'Qalyubia':'Qalyubia',
        'Qena':'Qena',
        'Red Sea':'Red Sea',
        'Sharqia':'Sharqia',
        'Sohag':'Sohag',
        'South Sinai':'South Sinai',
        'Suez':'Suez'
}

cities = (
        ('Alexandria','Alexandria'),
        ('Asyut','Asyut'),
        ('Beheira','Beheira') ,
        ('Beni Suef','Beni Suef'),
        ('Cairo','Cairo'),
        ('Dakahlia' , 'Dakahlia'),
        ('Damietta','Damietta'),
        ('Faiyum','Faiyum'),
        ('Gharbia','Gharbia'),
        ('Giza','Giza'),
        ('Ismailia','Ismailia'),
        ('Kafr El Sheikh','Kafr El Sheikh'),
        ('Monufia','Monufia'),
        ('Qalyubia','Qalyubia'),

)
